### ISSUE TITLE
saveState, searchBuilder, stateRestore don't play nice together.

### ISSUE THREAD

**Issue by gouldner** [DataTables/StateRestore#5] opened 2021-12-09 21:03 UTC
I want to implement searchBuilder and stateRestore but I also want to return to the last selected state.

So I implemented all three extensions and they are not working correctly.   I seem to randomly get a condition with enough testing where it returns to one of my saved states but then I can not reproduce the success.

Here is my test case for this issue.

http://live.datatables.net/wacajoso/2/edit

I find the following in my testing.
If I clear storage and start clean and then do the following, these are the results I get.
1) Save a State "State 1"
2) select that state and reload the page.
Result: "State 1" seems to be saved as it returns to "State 1"

1) Now create "State 2"
2) select that state and reload the page
Result: "State 1" is loaded which is incorrect.  saveState: true should have caused the page to return to the  previously selected state. 

1) Now remove "State 1"
2) Select state 2 and reload the page
Result: No state is returned it.   I think it wants to return to "State 1" but it's been removed.

**Comment by SandyDatatables** [comment] 2021-12-10 09:56
Hi @gouldner ,

This is a duplicate of [your post](https://datatables.net/forums/discussion/70894/staterestore-statesave-searchbuilder-integration-should-statesave-still-work#latest) in the forum. You aren't enabling `stateSave` but instead are trying to enable `saveState`.

Please try not to duplicate issues between the forum and GitHub. We do prefer issues to be posted in the forum rather than here.

Thanks,
Sandy

**Closed as completed by SandyDatatables** 2021-12-10 09:56 UTC

**Comment by gouldner** [comment] 2021-12-10 17:15
Yea, sorry about the duplicate.   At first I thought I was doing something wrong so I posted to forum for help then I decided it was a bug so I posted as an issue.   Now I know just to post to forum and either way you will see it.    Sorry for stupid mistake on my part.
